[build]
  base = "gas-monitor-web-v2"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_URL = "https://gas-monitor-backend-production.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
