-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ADMIN_PASSWORD_CHANGED';

-- AlterTable
ALTER TABLE "admin_users" ADD COLUMN "tokenVersion" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "mustChangePassword" BOOLEAN NOT NULL DEFAULT false;
